name: wedocp
services:
  postgres:
    container_name: postgres_db
    image: postgres:15
    environment:
      POSTGRES_DB: cp_database
      POSTGRES_USER: cp_user
      POSTGRES_PASSWORD: cp_password
    ports:
      - "5433:5432"  # Map external 5433 to container's default 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cp_user -d cp_database"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  migration:
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations
    command: 
      - -path
      - /migrations
      - -database
      - postgres://cp_user:cp_password@postgres:5432/cp_database?sslmode=disable
      - up
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:

networks:
  default:
    name: wedocp_default
